version = 0.1
[default.deploy.parameters]
stack_name = "project"
resolve_s3 = true
s3_prefix = "project"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HelloWorldFunction=284762931189.dkr.ecr.us-east-1.amazonaws.com/pproject939161ca/helloworldfunction19d43fc4repo"]
